name: Process Recipe Submissions

on:
  issues:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'recipe-submission')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run script to convert issue to recipe
      run: node .github/scripts/issue-to-recipe.js
      env:
        ISSUE_BODY: "${{ github.event.issue.body }}"
        ISSUE_TITLE: "${{ github.event.issue.title }}"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add recipe from issue: ${{ github.event.issue.title }}"
        git push
